<?php

/**
 * Implements hook_menu().
 */
function spy_glass_menu() {
  $items = [];
  $items['user/%node/spy_glass'] = [
    'title' => 'Spy Glass',
    'description' => 'Take a closer look',
    'page callback' => 'spy_glass_page',
    'page arguments' => [1],
    'access callback' => 'node_access',
    'access arguments' => ['view', 1],
    'type' => MENU_LOCAL_TASK,
  ];
  return $items;
}

/**
 * Implements hook_theme().
 */
function spy_glass_theme() {
  return [
    'spy_glass_item' => [
      'arguments' => ['title' => NULL, 'data' => NULL],
      'template' => 'spy-glass-item'
    ],
  ];
}

function _spy_glass_serious_spying_business($node) {
  $information = [];
  $information[] = [
    'title' => t('Title character count'),
    'data' => t('There are @num character in node', ['@num' => strlen($node->title)]),
  ];
  return $information;
}

function spy_glass_page($node) {
  $information = _spy_glass_serious_spying_business($node);

  $content = [];
  foreach ($information as $item) {
    $content[] = [
      '#type' => 'markup',
      '#markup' => theme('spy_glass_item', $item),
    ];
  }
  return $content;
}

function spy_glass_preprocess_spy_glass_item(&$variables) {
  $variables['title'] = check_plain($variables['title']);
  $variables['data'] = check_plain($variables['data']);
}
