<?php

/**
 * Implement hook_menu()
 */
function form_fun_menu() {
  $items = [];
  $items['form_fun/cake'] = [
    'title' => 'Cake or pie ?',
    'page callback' => 'form_fun_cake_page',
    'access arguments' => ['access content'],
    'file' => 'form_fun.cake.inc',
    'weight' => 1,
  ];

  $items['form_fun/tree'] = [
    'title' => "I'm lost",
    'page callback' => 'drupal_get_form',
    'page arguments' => ['form_fun_tree'],
    'access arguments' => ['access content'],
    'file' => 'form_fun.tree.inc',
    'weight' => 3,
  ];

  $items['form_fun/states'] = [
    'title' => "I'm lost",
    'page callback' => 'drupal_get_form',
    'page arguments' => ['form_fun_states_form'],
    'access arguments' => ['access content'],
    'file' => 'form_fun.state.inc',
    'weight' => 4,
  ];

  return $items;
}
