<?php

/*
 * Implemet hook_permission().
 */
function demo_permission() {
	return array(
    'administrator demo module' => array(
       'title' => t('Administrator demo module'),
       'description' => t('Perform administrative task for demo module'),
    ),
	);
}

/**
 * Implements hook_node_view();
 */
function demo_node_view($node, $view_mode, $langcode) {
	$node->content['demo_field'] = [
    '#type' => 'markup',
    '#markup' => '<p>' . t('demo text') . '</p>',
    '#weight' => -10, 
	];

	$node->content['demo_list'] = [
    '#items' => ['red', 'green', 'yello'],
    '#theme' => 'item_list',
    '#weight' => -9,
	];
}

/**
 * Implement hoo_menu();
 */
function demo_menu() {
    $items = [];

    $item['admin/reports/node-list'] = [
      'title' => 'List of Nodes',
      'description' => t('A list of nodes with publish status'),
      'page callback' => 'demo_node_list',
      'access arguments' => ['administrator content'],
    ];

    return $items;
}

function demo_node_list() {
  return 'Its works';
}